name: Release on Push Tag

permissions:
  contents: write
  actions: write

on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build Production
    runs-on: macos-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      #      - name: Install xcode tools
      #        run: xcode-select --install

      # 解码并导入证书
      - name: Import Certificate
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
        run: |
          # 创建临时钥匙串
          security create-keychain -p "$APPLE_KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$APPLE_KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

          # 导入证书到钥匙串
          echo "$CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 -k build.keychain -P "$CERT_PASSWORD" -T /usr/bin/codesign

          # 配置证书权限
          security set-key-partition-list -S apple-tool:,apple: -s -k "$APPLE_KEYCHAIN_PASSWORD" build.keychain

      - name: Retrieve the profile and decode it to a file
        env:
          CERTIFICATE_BASE64: ${{ secrets.PROFILE_DATA }}
        run: |
          echo $CERTIFICATE_BASE64 | base64 --decode > build/profilesshconfigeditor.provisionprofile

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 安装依赖
      - run: npm ci

      - name: create_release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: "${{ github.ref_name }}"
          release_name: "${{ github.ref_name }}"
          body: "Release ${{ github.ref_name }}"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      # 构建 arm64 版本
      - run: npm run make:all
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      # 构建 x64 版本
      - run: npm run make:all:x64
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}